apiVersion: v1
kind: Service
metadata:
  name: angular-webapp-deploy
  namespace: project-ma
spec:
  type: LoadBalancer
  selector:
    app: angular-webapp-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80